### ISSUE TITLE
NoSuchElementException in Snyk plugin v2.2.1

### ISSUE THREAD

**Issue by gcpdev** [snyk/snyk-intellij-plugin#153]
Hi all,

I am trying to use the Snyk plugin with my SSO credentials within my company. Here are my settings:

![Intellij settings](https://i.imgur.com/bpBO1x1.png)

Authentication via button does not work, so I am using the token.

And when I go to the Snyk tab, it is enabled (which means, it does not ask me for authentication anymore). Then I once hit "Run scan", I get the following:

![Intellij exception](https://imgur.com/XyO4DTs.png)

Full stacktrace:
`java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:71)
	at io.snyk.plugin.services.SnykCliService.convertRawCliStringToCliResult(SnykCliService.kt:64)
	at io.snyk.plugin.services.SnykCliService.scan(SnykCliService.kt:47)
	at io.snyk.plugin.services.SnykTaskQueueService$scheduleCliScan$1.run(SnykTaskQueueService.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)`

If there is anything else I can provide you to support your investigation, please let me know. 
Thanks on beforehand!

**Comment by ArtsiomCh** [comment]
Hey @gcpdev ! Thanks for reporting!
I dive a bit into the code and seems to get why it happened but would like to investigate the root cause of that issue. Would be helpful to have project where you've got this Exception. Is it publicly available (GitHub) or it's a close source project?
Also would be very helpful to have you Idea's log file: [Locating IDE log files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) You can attach it here or send it privately to support@snyk.io (Please, specify in your email an ID or a link to this issue) email to avoid expose any private info here.

**Comment by gcpdev** [comment]
Hi @ArtsiomCh, thanks for your quick return. It is a private project hosted in AzureDevOps. I have just sent the logs via e-mail.

**Comment by ArtsiomCh** [comment]
@gcpdev  got the log, Thank you!
Few more questions:

1. do you see notification (right bottom corner)  from Snyk that says: `Not able to run CLI, try again later.` ?
2. are you able to run [manually installed](https://support.snyk.io/hc/en-us/articles/360003812538-Install-the-Snyk-CLI) CLI for that project: `snyk-macos test --json --org=xx-sit-odj-dconnector` and see any output?

**Comment by ArtsiomCh** [comment]
Hey @gcpdev 
The fix is merged into master and should be released with next plugin version. Probably coming week, but no commitments :)
