### ISSUE TITLE
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: io.snyk.snyk-intellij-plugin]

### ISSUE THREAD

**Issue by BorzdeG** [snyk/snyk-intellij-plugin#33]
IntelliJ IDEA 2020.1 EAP (Ultimate Edition) Build #IU-201.6251.22

plugin version: 0.1.2

```
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: io.snyk.snyk-intellij-plugin]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:171)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:527)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:515)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1497)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$null$2(Preloader.java:75)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:202)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:191)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:449)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:190)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:430)
	... 21 more
Caused by: java.lang.NoSuchFieldError: HideDownPart
	at io.snyk.plugin.ui.actions.SnykToggleGroupDisplayAction.<init>(SnykToggleGroupDisplayAction.scala:9)
	... 26 more
```

**Comment by aldanchenko** [comment]
Hello Victor,

Thank you for this important information! We will check it as soon as possible!

Best regards,
Alex.

**Comment by aldanchenko** [comment]
Hello @BorzdeG 

Could you, please, share details from IntelliJ "About IntelliJ IDEA-EAP" menu item?

Thank you!
Alex.

**Comment by BorzdeG** [comment]
IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.6251.22, built on March 12, 2020
IntelliJ IDEA EAP User
Expiration date: April 11, 2020
Runtime version: 11.0.6+8-b765.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: KotlinTIOBE, PlantUML integration, String Manipulation, com.ankit.mahadik.json.dart.class, com.github.leomillon.uuidgenerator, com.github.novotnyr.jwt-intellij-plugin, com.github.shchurov.gradlestop, com.idlesign.qrcoder, com.vladsch.git-file-case-fixer, zielu.gittoolbox, Lombook Plugin, com.herbert.george.dart.extensions, com.intellij.bigdecimal-folding, com.jetbrains.embeddedProjectJdk, com.viartemev.requestmapper, com.yhuang.code-smell-detector, de.docksnet.puml.syntaxchecker, launch-url-from-string, marcglasberg.HibernateInspectionsPlugin, org.jetbrains.plugins.hocon, org.pmesmeur.sketchit, woaini.liquibase.plugin, com.intellij.plugins.macoskeymap, com.blackbuild.intellij.maven-wrapper-support, com.intellij.selenium, com.sonnk.iterm, detekt, fr.dco.kotlin.vcs-kotlin-converter, hunspell, ideanginx9, in.thekalinga.snippet.intellij, indent-rainbow.indent-rainbow, lermitage.intellij.extra.icons, name.kropp.intellij.makefile, org.intellij.RegexpTester, BashSupport, com.intellij.lang.jsgraphql, AWSCloudFormation, ru.adelf.idea.dotenv, Dart, andrasferenczi.dart-data-plugin, com.localizely.flutter-intl, com.mobiledi.flutter_plugins, io.flutter, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, com.layernet.plugin.adbwifi, net.aquadc.mike.plugin, cn.yiiguxing.plugin.translate, de.mariushoefler.flutter_enhancement_suite, com.gmail.blueboxware.extsee, com.jetbrains.packagesearch.intellij-plugin, kotlin-i18n-write-action, kotlintest-plugin-intellij, net.lagerwey.cucumber-kotlin, org.asciidoctor.intellij.asciidoc, org.apache.camel, com.intellij.kubernetes, org.semonte.intellij.swagger, ru.itbasis.plugins.intellij.hashGenerator

**Comment by aldanchenko** [comment]
Hello @BorzdeG 

Could you, please, try this version.

Regards,
Alex.

[snyk-intellij-plugin-0.2.0.zip](https://github.com/snyk/snyk-intellij-plugin/files/4348623/snyk-intellij-plugin-0.2.0.zip)

**Comment by BorzdeG** [comment]
Yes, now there is no error

**Comment by aldanchenko** [comment]
Thank you @BorzdeG for the reply and feedback!
