### ISSUE TITLE
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by costalfy** [snyk/snyk-intellij-plugin#8]
Hi, 
we use Zscaler proxy and i have this issue on intellij 2019.1.3
```
An Error Occurred
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
This is the stack trace in intellij log file:
```java
2019-06-04 09:40:56,134 [  40082]   WARN - ugin.embeddedserver.MiniServer - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.softwaremill.sttp.HttpURLConnectionBackend.writeBody(HttpURLConnectionBackend.scala:76)
	at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:39)
	at com.softwaremill.sttp.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:18)
	at com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:17)
	at com.softwaremill.sttp.FollowRedirectsBackend.followRedirect(FollowRedirectsBackend.scala:57)
	at com.softwaremill.sttp.FollowRedirectsBackend.$anonfun$followRedirect$2(FollowRedirectsBackend.scala:37)
	at scala.Option.fold(Option.scala:158)
	at com.softwaremill.sttp.FollowRedirectsBackend.followRedirect(FollowRedirectsBackend.scala:33)
	at com.softwaremill.sttp.FollowRedirectsBackend.$anonfun$sendWithCounter$1(FollowRedirectsBackend.scala:21)
	at com.softwaremill.sttp.IdMonad$.flatMap(MonadError.scala:44)
	at com.softwaremill.sttp.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
	at com.softwaremill.sttp.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:12)
	at com.softwaremill.sttp.RequestT.send(RequestT.scala:224)
	at io.snyk.plugin.client.StandardApiClient.$anonfun$runRaw$2(ApiClient.scala:97)
	at io.snyk.plugin.client.StandardApiClient.retry(ApiClient.scala:68)
	at io.snyk.plugin.client.StandardApiClient.$anonfun$runRaw$1(ApiClient.scala:95)
	at scala.util.Success.flatMap(Try.scala:247)
	at io.snyk.plugin.client.StandardApiClient.runRaw(ApiClient.scala:75)
	at io.snyk.plugin.client.StandardApiClient.runScan(ApiClient.scala:145)
	at io.snyk.plugin.ui.state.SnykPluginState.$anonfun$performScan$6(SnykPluginState.scala:112)
	at scala.util.Success.flatMap(Try.scala:247)
	at io.snyk.plugin.ui.state.SnykPluginState.$anonfun$performScan$5(SnykPluginState.scala:112)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:76)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:165)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 41 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 47 more
2019-06-04 09:40:56,144 [  40092]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 04-06-19 09:40) 
2019-06-04 09:40:56,223 [  40171]   INFO - j.ide.ui.OptionsTopHitProvider - 366 ms spent on EDT to cache options in project 
2019-06-04 09:40:56,472 [  40420]   INFO - o.snyk.plugin.ui.SnykHtmlPanel - done loading start page from http://localhost:58918/vulnerabilities? 
```

**Comment by yuliabaron** [comment]
Hi,
Sorry for the late reply. We'll attend it in our next version

**Comment by aldanchenko** [comment]
Hi @costalfy 

We released new plugin version - https://plugins.jetbrains.com/plugin/10972-snyk-vulnerability-scanner/versions/stable/107249. 

Maybe you already tried it? Is this issue still exists?

Best regards,
Alex

**Comment by costalfy** [comment]
hi,
I'm sorry, but I can't test anymore because I quit my company in September 2020 and we don't use zscaler anymore.

Regards

**Comment by aldanchenko** [comment]
Hi @costalfy 

Thanks for quick reply. And I'm sad to hear about your job. If you don't mind I'll close this issue for now.

Best regards,
Alex

**Comment by kasiprasath** [comment]
> Hi @costalfy
> 
> We released new plugin version - https://plugins.jetbrains.com/plugin/10972-snyk-vulnerability-scanner/versions/stable/107249.
> 
> Maybe you already tried it? Is this issue still exists?
> 
> Best regards,
> Alex

hi,

i am facing the same issue, we are using Zscalar. I installed this plugin and after apply the plugin, the pop up dialog asked to accept the certificate provided by zscalar. Still facing the issue sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
